baseURL = 'https://garbhank.github.io/album-club/'
author = "garbhan"
languageCode = 'en-us'
title = 'album club'
canonifyURLs = true

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "years"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 10

[params]
  [params.author]
    email = 'garbhan@icloud.com'
    name = 'Garbhan Kenneally'

